name: Rename Wordle Channel

on:
  schedule:
    - cron: "0 1 * * *"    # 2:00 AM Lisbon (1:00 UTC)
    - cron: "30 6 * * *"   # 7:30 AM Lisbon (1:00 UTC)
    - cron: "30 12 * * *"  # 13:30 PM Lisbon (12:30 UTC)
    - cron: "30 15 * * *"  # 16:30 PM Lisbon (12:30 UTC)
  workflow_dispatch:        # Allows you to trigger it manually too

jobs:
  rename:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: python bot.py
